config/routes.rb
Proyectoruby::Application.routes.draw do
  resources :cars

    
  resources :brands
   devise_for :users
  get '/somos' => 'header#somos'
 

   root 'brands#index'

  

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :cars
end

app/models/car.rb
class Car < ActiveRecord::Base
	belongs_to :brand
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
     #@brands = Brand.paginate(:page => params[:page], :per_page => 1)
    @brands = Brand.all
  @brands=@brands.paginate(:page => params[:page], :per_page => 2)
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brand }
      else
        format.html { render action: 'new' }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:id,:image, :description, :phone)
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    if params[:id].nil?
      @cars = Car.paginate(:page => params[:page], :per_page => 3)
    else
      @cars = Car.where(:brand_id => params[:id])
      @cars=@cars.paginate(:page => params[:page], :per_page => 1)
      #@cars = Car.where(:brand_id => params[:id])
      
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    if params.nil?
      @cars = Car.all
    else
         @cars = Car.all
    end
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
      
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:image, :Description, :km, :brand_id)
    end
end

app/controllers/header_controller.rb
class HeaderController < ApplicationController

	def somos 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/header_helper.rb
module HeaderHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_area :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<div id="titulomarca"><h1>ACTUALLY BRANDS</h1></div>


   

  
  <div id="atributos">
    
      <li class="atributon">Image</li>
      <li class="atributon">Brand</li>
      <li class="atributon">Description</li>
      
    </div>
  


  <tbody>
    <% @brands.each do |brand| %> 
    <div class="brands_object">
             
        <%= link_to   image_tag(brand.image , :size => '350') , :controller => "cars", :action => "index", :id => brand.id %> 
        <div class="atributomarca"> <%= brand.description %> </div>
        <div class="atributomarca"> <%= brand.phone %>        </div>
 

        <div class="atributomarca">
        <%= link_to 'Show', brand %>
        
        <% if !current_user.nil? %>
         <%= link_to 'Edit', edit_brand_path(brand) %>
         <%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
     </div>
      
         <%end%>
        <% end %>
     </tbody> 




<div id="crearmarca">
   <% if !current_user.nil? %>
     <%= link_to 'New Brand', new_brand_path %>
</div>
  <%end%>

<div id="paginate"> 
  <%= will_paginate @cars %> 
  </div>

app/views/brands/new.html.erb
<div id="crearmarca">
  <h1>New brand</h1>
</div>
<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@brand.image , :size => '100') %>
</p>

<p>
  <strong>Description:</strong> 
  <%= @brand.description %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @brand.phone %>
</p>

<% if !current_user.nil?%>
<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%end%>
<%= link_to 'Back', brands_path %>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :km %><br>
    <%= f.number_field :km %>
  </div>
  <div class="field">
    <%= f.label :brand_id %><br>
    <%= f.number_field :brand_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
 <div id="titulomarca"> 
    <h1>Actually Cars</h1>
 </div>

   
      
     <div id="atributos">
    
      <li class="atributon"> Image       </li>
      <li class="atributon"> Description </li>
      <li class="atributon"> Prize       </li>
      <li class="atributon"> Brand       </li>
    </div>
   
  <tbody>
    <% @cars.each do |car| %>
         <div class="cars_object">
         
          
    
        <%= image_tag(car.image ,:width => '300') %>

         <div class="descripcioncoche">  <%= car.Description %>      </div>
          <div class="atributocoche"> <%= car.km %>                 </div>
          <div class="atributocoche"> <%= car.brand.description%>   </div>
         <div class="acciones">  <%= link_to 'Show', car %>    </div>
          <div class="acciones"> <%= link_to 'Edit', car %>    </div>
           <div class="acciones"><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' }%> </div>
      
       </div>
    <% end %>
   
  </tbody>


<div id="crearmarca">
<% if !current_user.nil? %>
    <%= link_to 'New Brand', new_brand_path %>
    <%= link_to 'New Car', new_car_path %>
    </div>
<%end%>

<div id="paginate">
<%= will_paginate @brands %>
</div>
   

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@car.image, :width => '500') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @car.Description %>
</p>

<p>
  <strong>Km:</strong>
  <%= @car.km %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand_id %>
</p>


<% if !current_user.nil?%>
<%= link_to 'Edit',  edit_car_path(@car)%> |
<%end%>
<%= link_to 'Back', cars_path %>

app/views/header/somos.html.erb
<html>
<body>

   <div  id="titulomarca">
       <h1> El Cliente es lo primero</h1>
   </div>
 
 
    <div id="imagensomos"> 
          <%= image_tag('logotipo.jpeg' , :size =>'170')%>  
    </div>

   <div id="descripcionsomos"> 
                Nuestra web fue creada en 2011 , el motivo que nos llevo a hecha           
                fue básicamente que queríamos ofrecer al cliente un servicio donde pudiera 
                ver los precios y coches de cada marca.                                   
                

                Actualmente, disponemos de una ubicación donde vendemos coches de segunda mano. 
                En un futuro nos gustaría  poder ofrecerles a los clientes                      
                un servicio de compra online de coches de segunda mano  a través de             
                un buscador sencillo cuya búsqueda sea inmediata.                               

                
   </div>
   <div id="datossomos"> 
                  Datos de la empresa          

                   Nombre: RARACAR             
                   Telefono: 645123153        
                   Dirección: C/Alcala 25       
                   Provincia: Madrid            
                   Email:raracar@hotmail.com 
             
   </div>
     
     


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RUBY</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>


     <div class="Menu_UpHtml">
        <div id="Menu_UpHtml1">
           <ul> 
            <div class="nose"> 
               <li> <%= link_to 'About' , somos_path %>              </li>
            </div>
            <div class="nose"> 
               <li> <%= link_to 'See Cars' , cars_path  %>            </li>
            </div>
            <div class="nose">
            <li> <%= link_to 'See Brands' , brands_path %>        </li>
            </div>
            <div class="pepito"> 
                  <li>
                    <% if user_signed_in? %>
                       Signed in as <%= current_user.email %>. Not you?
                       <%= link_to "Sign out", destroy_user_session_path , :method => :delete %>
                     <% else %>
                        <%= link_to "Sign up", new_user_registration_path %> or
                        <%= link_to "Sign in", new_user_session_path %>
                      <% end %>
                  </li>
            </div>
          </ul>
       </div>
     </div>

    
     
     <div class="body">
         <%= yield %>
     </div>

<div id="pie">
   
     <div id="pie1">
       
           <ul>
              <li class ="piederechos">  CONDICIONES DE USO  </li>
              <li class ="piederechos">  PROTECCION DE DATOS </li>
              <li class ="piederechos">  DERECHOS DE AUTOR   </li>
              <li class ="piederechos">  CONTACTO            </li>
          </ul> 
     </div>

    <div id="imagenabajo"> 
       <%= link_to image_tag('logotipo.jpeg' , :size =>'150') ,cars_path %>  
    </div>

<div id="parteabajo">

      <div id="pie_abajo">       
         <ul>  
             
           <li class ="pieinfo"> NOMBRE:     RARACAR           </li>
           <li class ="pieinfo"> DIRECCION:  C/ALCALA 25       </li>
           <li class ="pieinfo"> CP:         28823             </li>          
           <li class ="pieinfo"> TELEFONO:   645123153       </li>   

         </ul>
     </div>

     <div class="hola">
       <ul>
          <li class="boton"> <%= link_to  image_tag('facebook.png',:size => '50'),"http://www.facebook.com",
                :target => '_blank'%>         </li>
           <li class="boton"> <%= link_to  image_tag('twitter.png',:size =>  '50'),"http://www.twitter.com",
                :target => '_blank'%>         </li>
          <li  class="boton" > <%= link_to  image_tag('youtube.jpeg' ,:size => '50'),"http://www.youtube.com", 
                :target => '_blank'%>         </li>
          <li  class="boton"> <%= link_to image_tag('instagram.png',:size => '50'),"http://www.instagram.com",
                :target => '_blank'%>         </li> 
       </ul>
      </div>
   </div>
</div>


</body>
</html>